### ISSUE TITLE
caught variable unused at math.cpp line 226, causes compile to fail on windows

### ISSUE THREAD

**Issue by erg** [factor/factor#1549]
```
math.cpp
vm\math.cpp(226): error C2220: warning treated as error - no 'object' file generated
vm\math.cpp(226): warning C4101: 'error': unreferenced local variable
```

@jonenst

**Comment by erg** [comment]
Can we just do this?

```c++
-  } catch (const runtime_error& error) {
+  } catch (...) {
```

**Comment by jonenst** [comment]
This ? From http://stackoverflow.com/questions/7159348/disable-single-warning-error

```c++
try
{
    // ...
}
catch(const your_exception_type &) // type specified but no variable declared
{
    // ...
}
```

compiles fine with gcc 4.8.4 and clang 3.4.1 ubuntu 14.04

**Comment by erg** [comment]
Visual Studio 15! :japanese_ogre:

**Comment by jonenst** [comment]
So does this fix it on Visual Studio 15?
```diff
-  } catch (const runtime_error& error) {
+  } catch (const runtime_error&) {
```
it's the correct thing to do
