### ISSUE TITLE
vm function shrink_to_fit() missing

### ISSUE THREAD

**Issue by erg** [factor/factor#1624]
```
ergmac:factor erg$ [master*] make
/Applications/Xcode.app/Contents/Developer/usr/bin/make `./build.sh make-target`
/Applications/Xcode.app/Contents/Developer/usr/bin/make factor factor-ffi-test factor-lib macosx.app CONFIG=vm/Config.macosx.x86.64
c++ -c -Wall -pedantic -DFACTOR_VERSION="0.98" -DFACTOR_GIT_LABEL="heads/master-c100d2256d82d79b463e93c9e73d536fce0587b5" -fomit-frame-pointer -mmacosx-version-min=10.5 -m64 -O3 -g -std=c++11 -o vm/sampling_profiler.o vm/sampling_profiler.cpp
vm/sampling_profiler.cpp:74:11: error: no member named 'shrink_to_fit' in 'std::vector<factor::profiling_sample,
      std::allocator<factor::profiling_sample> >'
  samples.shrink_to_fit();
  ~~~~~~~ ^
vm/sampling_profiler.cpp:75:21: error: no member named 'shrink_to_fit' in 'std::vector<unsigned long, std::allocator<unsigned long>
      >'
  sample_callstacks.shrink_to_fit();
  ~~~~~~~~~~~~~~~~~ ^
2 errors generated.
make[2]: *** [vm/sampling_profiler.o] Error 1
make[1]: *** [macosx-x86-64] Error 2
make: *** [default] Error 2


ergmac:factor erg$ [master*] ag shrink_to_fit
vm/sampling_profiler.cpp
74:  samples.shrink_to_fit();
75:  sample_callstacks.shrink_to_fit();
```

**Comment by erg** [comment]
@bjourne

**Comment by bpollack** [comment]
@erg I'm pretty sure the issue is you're using the C++11 language, but
not the C++11 library. Not at a computer, but when I am, I'll look up
what you need to change in that invocation.

**Comment by erg** [comment]
@bpollack You're right. And c++ library doesn't play with 10.5 compatibility, you need 10.7 and up.

One workaround is the ``swap`` trick.

https://stackoverflow.com/questions/253157/how-to-downsize-stdvector

```
# error: 10.5, c++11, libc++
ergmac:factor erg$ [master*] c++ -c -Wall -pedantic -DFACTOR_VERSION="0.98" -DFACTOR_GIT_LABEL="heads/master-c100d2256d82d79b463e93c9e73d536fce0587b5" -fomit-frame-pointer -mmacosx-version-min=10.5 -m64 -O3 -g -std=c++11 -stdlib=libc++ -o vm/sampling_profiler.o vm/sampling_profiler.cpp
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

# ok: c++11, libc++
ergmac:factor erg$ [master*] c++ -c -Wall -pedantic -DFACTOR_VERSION="0.98" -DFACTOR_GIT_LABEL="heads/master-c100d2256d82d79b463e93c9e73d536fce0587b5" -fomit-frame-pointer -m64 -O3 -g -std=c++11 -stdlib=libc++ -o vm/sampling_profiler.o vm/sampling_profiler.cpp

# ok: c++11
ergmac:factor erg$ [master*] c++ -c -Wall -pedantic -DFACTOR_VERSION="0.98" -DFACTOR_GIT_LABEL="heads/master-c100d2256d82d79b463e93c9e73d536fce0587b5" -fomit-frame-pointer -m64 -O3 -g -std=c++11 -o vm/sampling_profiler.o vm/sampling_profiler.cpp

# the one we use right now
# error: 10.5, c++11
ergmac:factor erg$ [master*] c++ -c -Wall -pedantic -DFACTOR_VERSION="0.98" -DFACTOR_GIT_LABEL="heads/master-c100d2256d82d79b463e93c9e73d536fce0587b5" -fomit-frame-pointer -mmacosx-version-min=10.5 -m64 -O3 -g -std=c++11 -o vm/sampling_profiler.o vm/sampling_profiler.cpp
vm/sampling_profiler.cpp:74:11: error: no member named 'shrink_to_fit' in 'std::vector<factor::profiling_sample,
      std::allocator<factor::profiling_sample> >'
  samples.shrink_to_fit();
  ~~~~~~~ ^
vm/sampling_profiler.cpp:75:21: error: no member named 'shrink_to_fit' in 'std::vector<unsigned long, std::allocator<unsigned long>
      >'
  sample_callstacks.shrink_to_fit();
  ~~~~~~~~~~~~~~~~~ ^
2 errors generated.
```

**Comment by mrjbq7** [comment]
@erg it was swapping before, this moves to a modern way to do it I think.

**Comment by erg** [comment]
That would be fine if we agree to stop supporting 10.5 and instead target 10.7.

**Comment by bpollack** [comment]
I'm really okay with that. 10.5 isn't supported and has tons of security holes. I don't even think 10.7 is better on that front, but it makes targeting 10.5 a nonstarter.

**Comment by bjourne** [comment]
I thought `shrink_to_fit` would work since we upgraded to c++11. But if it's not available on modern compilers I'll revert.

**Comment by erg** [comment]
It's there, but not with OSX 10.5 support.

I'm trying to support OSX 10.7 but my first attempt spews this:

https://paste.factorcode.org/paste?id=3872

**Comment by erg** [comment]
``-mmacosx-version-min=10.7`` and ``-mmacosx-version-min=10.8`` both spew that error, but ``-mmacosx-version-min=10.9`` works.

10.9 it is!

**Comment by mrjbq7** [comment]
LOL

**Comment by jonenst** [comment]
On http://concatenative.org/wiki/view/Factor/Requirements , it still says "Factor works on Mac OS X 10.5 (Leopard) and higher."

I tried compiling on 10.7 (with xcode 4.6.3 and http://adcdownload.apple.com/Developer_Tools/command_line_tools_os_x_lion_for_xcode__april_2013/xcode462_cltools_10_76938260a.dmg ) and got the following errors:
  - the semver version is not parsed correctly because Apple changes the version numbers:
```
major 4
minor 2
patch 0
special (clang-425.0.28) (based on LLVM 3.2svn)
```
Note, On Ubuntu, I get
```
CLANG_MAJOR 3
CLANG_MINOR 4
CLANG_PATCH 0
CLANG_SPECIAL 1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
```

  - the missing shrink to fit errors
  - after commenting the shrink to fit, 
```
./build.sh: line 606:  6507 Segmentation fault: 11  ./$FACTOR_BINARY -i=$BOOT_IMAGE
```

Note: the binary distribution of factor also segfaulted..

**Comment by bjourne** [comment]
What does `clang --version` say on osx?

**Comment by jonenst** [comment]
@erg so 10.9 is the requirement now? I guess it's enough to just update the wiki.

Also, can we prevent the failed compilation (because of the missing shrink_to_fit function) by checking something ? We already check clang_version >= 3.1 in build.sh. Not sure how we want to check the version of the C++ library.. A C preprocessor macro ? A ./configure style check ?
